{
	"version": 1531492840,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/iboladesbão-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/spritefont.png",
		"images/tiledbackground.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/bg-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/pop1.ogg",
		"media/pop2.ogg",
		"media/pop3.ogg",
		"media/010614songidea(copycat).m4a",
		"media/010614songidea(copycat).ogg",
		"media/too lazy to put a name on this track.m4a",
		"media/too lazy to put a name on this track.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}