{
	"version": 1546428522,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/platform-sheet0.png",
		"images/obotãomovimento-sheet0.png",
		"images/telademenu2x-sheet0.png",
		"images/bg-sheet0.png",
		"images/cometaamarelo-sheet0.png",
		"images/cometaamarelo-sheet1.png",
		"images/prancheta1cópia-sheet0.png",
		"images/gameover-sheet0.png",
		"images/p-sheet0.png",
		"images/p-sheet1.png",
		"images/vespa-sheet0.png",
		"images/shild-sheet0.png",
		"images/ocometas-sheet0.png",
		"images/fade-sheet0.png",
		"images/pause-sheet0.png",
		"images/placar-sheet0.png",
		"images/play-sheet0.png",
		"images/restart-sheet0.png",
		"images/menu-sheet0.png",
		"images/pausefundo-sheet0.png",
		"images/continue-sheet0.png",
		"images/info-sheet0.png",
		"images/creditos-sheet0.png",
		"images/score-sheet0.png",
		"images/pgrande-sheet0.png",
		"images/pgrande-sheet1.png",
		"images/escudo-sheet0.png",
		"images/somdesligado-sheet0.png",
		"images/somdesligado-sheet1.png",
		"images/instruções-sheet0.png",
		"media/bogart vgm - scifi concentration (looped).ogg",
		"media/pulo.m4a",
		"media/pulo.ogg",
		"media/bit space (loopable).ogg",
		"media/lost signal main theme (wip)_1.ogg",
		"media/sci-fi drone.ogg",
		"media/enquanto estiver com o escudo.m4a",
		"media/enquanto estiver com o escudo.ogg",
		"media/botÕes.m4a",
		"media/botÕes.ogg",
		"media/inimigo-morte.m4a",
		"media/inimigo-morte.ogg",
		"media/powerup.m4a",
		"media/powerup.ogg",
		"media/som de asas(finzalizado).m4a",
		"media/som de asas(finzalizado).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}