{
	"version": 1560367912,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/obotoes-sheet0.png",
		"images/obotoes-sheet1.png",
		"images/obotoes-sheet2.png",
		"images/ifundolayers-sheet0.png",
		"images/iconfirmacao-sheet0.png",
		"images/ifundolayout-sheet0.png",
		"images/iprodutos-sheet0.png",
		"images/iprodutos-sheet1.png",
		"images/bembaralhar-sheet0.png",
		"images/iquadrofundo-sheet0.png",
		"images/iquadrofundo-sheet1.png",
		"images/iquadrofundo-sheet2.png",
		"images/iprodutoss-sheet0.png",
		"images/iprodutoss-sheet1.png",
		"images/iprodutoss-sheet2.png",
		"images/iprodutoseb-sheet0.png",
		"images/iprodutoseb-sheet1.png",
		"images/iprodutoseb-sheet2.png",
		"images/iprodutosab-sheet0.png",
		"images/iprodutosab-sheet1.png",
		"images/iprodutosab-sheet2.png",
		"images/iprodutosd-sheet0.png",
		"images/iprodutosd-sheet1.png",
		"images/iprodutosd-sheet2.png",
		"images/idicas-sheet0.png",
		"images/ilike-sheet0.png",
		"images/ilike-sheet1.png",
		"images/ibarradebaixolike-sheet0.png",
		"images/ibarradebaixodislike-sheet0.png",
		"images/ibarradecimalike-sheet0.png",
		"images/ibarradecimadislike-sheet0.png",
		"images/iobjetosmenu-sheet0.png",
		"images/iobjetosmenu-sheet1.png",
		"images/particles.png",
		"images/particles2.png",
		"images/ititulo-sheet0.png",
		"images/irelogio-sheet0.png",
		"images/ivalortotal-sheet0.png",
		"images/igameover-sheet0.png",
		"images/iapto-sheet0.png",
		"images/ivefc-sheet0.png",
		"images/ivefc-sheet1.png",
		"images/ivefc-sheet2.png",
		"images/i2cfve-sheet0.png",
		"images/instruÇÕes-sheet0.png",
		"images/telainstruçoes-sheet0.png",
		"images/iatt-sheet0.png",
		"images/tfase-sheet0.png",
		"images/bf1-sheet0.png",
		"media/clickpraqqcoisa.m4a",
		"media/clickpraqqcoisa.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/inserindo moeda.m4a",
		"media/inserindo moeda.ogg",
		"media/musica da fase.m4a",
		"media/musica da fase.ogg",
		"media/musica do menu.m4a",
		"media/musica do menu.ogg",
		"media/passar de fase.m4a",
		"media/passar de fase.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}