{
	"version": 1546460466,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/monsterpipebaixo-sheet0.png",
		"images/monster-sheet0.png",
		"images/bg.png",
		"images/chao.png",
		"images/teto.png",
		"images/cooltext-sheet0.png",
		"images/cooltext2-sheet0.png",
		"images/pontuacao1.png",
		"images/contagem-sheet0.png",
		"images/botaorecar-sheet0.png",
		"images/osensorpoint-sheet0.png",
		"images/fundo-sheet0.png",
		"images/cooltext3-sheet0.png",
		"images/cooltext4-sheet0.png",
		"images/cooltext5-sheet0.png",
		"images/cooltext6-sheet0.png",
		"media/monstercollision.m4a",
		"media/monstercollision.ogg",
		"media/monsterjump.m4a",
		"media/monsterjump.ogg",
		"media/monsterpoint.m4a",
		"media/monsterpoint.ogg",
		"media/video dungeon boss.m4a",
		"media/video dungeon boss.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}